services:
  app:
    image: ttionya/docker-pull-statistics:latest
    container_name: docker-pull-statistics
    restart: unless-stopped
    # environment:
    #  NUXT_APP_BASE_URL: /
    #  ACCESS_TOKEN:
    #  DATABASE_URI: 'sqlite:data/database.sqlite'
    ports:
      - '3000:3000'
    volumes:
      - ./data:/app/data
