services:
  app:
    image: ttionya/docker-pull-statistics:latest
    container_name: docker-pull-statistics
    restart: unless-stopped
    # environment:
      # - ACCESS_TOKEN=
      # - NUXT_APP_BASE_URL=/sub/
    ports:
      - '3000:3000'
    volumes:
      - ./data:/app/data
